# Generated by Django 5.1.3 on 2024-11-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('audio_file', models.FileField(upload_to='static/audio/')),
                ('audio_link', models.URLField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
